package g56080.same.model;

import java.util.function.IntUnaryOperator;

/**
 * A counter used to accumulate an integer score based on a given unary operator function.
 */
public class ScoreCounter{
    
    private int score;
    private final IntUnaryOperator func;

    /**
     * Constructs a new score counter using the given unary operator function. This function
     * is used to compute and accumulate new scores.
     *
     * @param func the unary operator function to be used
     */
    public ScoreCounter(IntUnaryOperator func){
        this.func = func;
    }

    /**
     * Constructs a copy of the given score counter.
     *
     * @param sc the score counter to copy
     */
    public ScoreCounter(ScoreCounter sc){
        score = sc.score;
        func = sc.func;
    }

    /**
     * Computes the score to accumulate for the given integer value using the
     * unary operator function.
     *
     * @param value the value to compute
     *
     * @return the integer score generated by the function for the given value.
     */
    public int compute(int value){
        return func.applyAsInt(value);
    }

    /**
     * Adds the given integer value to this score counter using the unary operator
     * function.
     *
     * @param value the integer value to add
     */
    public void add(int value){
        score += func.applyAsInt(value);
    }

    /**
     * Gets the integer score associated to this counter.
     *
     * @return the integer score of this counter.
     */
    public int asInt(){
        return score;
    }

    /**
     * Gets the unary operator function associated to this score counter.
     *
     * @return the unary operator function of this score counter.
     */
    public IntUnaryOperator getCalculatorFunc(){
        return func;
    }
}

